CC = gcc
CFLAGS = -W -Wall

all : case1 case2 case3 case4 case5 case6 case7 case8 case9 case10 case11 case12 case13 case14 case15 case16

case1 : case1.c
	$(CC) $(CFLAGS) -o $@ $^

case2 : case2.c
	$(CC) $(CFLAGS) -o $@ $^

case3 : case3.c
	$(CC) $(CFLAGS) -o $@ $^

case4 : case4.c
	$(CC) $(CFLAGS) -o $@ $^

case5 : case5.c
	$(CC) $(CFLAGS) -o $@ $^

case6 : case6.c
	$(CC) $(CFLAGS) -o $@ $^

case7 : case7.c
	$(CC) $(CFLAGS) -o $@ $^

case8 : case8.c
	$(CC) $(CFLAGS) -o $@ $^

case9 : case9.c
	$(CC) $(CFLAGS) -o $@ $^

case10 : case10.c
	$(CC) $(CFLAGS) -o $@ $^

case11 : case11.c
	$(CC) $(CFLAGS) -o $@ $^

case12 : case12.c
	$(CC) $(CFLAGS) -o $@ $^

case13 : case13.c
	$(CC) $(CFLAGS) -o $@ $^

case14 : case14.c
	$(CC) $(CFLAGS) -o $@ $^

case15 : case15.c
	$(CC) $(CFLAGS) -o $@ $^

case16 : case16.c
	$(CC) $(CFLAGS) -o $@ $^

clean :
	rm -rf case*.o
	./case1
	./case2
	./case3
	./case4
	./case5
	./case6
	./case7
	./case8
	./case9
	./case10
	./case11
	./case12
	./case13
	./case14
	./case15
	./case16
